### ISSUE TITLE
Rename doesn't rename all occurencies

### ISSUE THREAD

**Issue by sbushmanov** [scalameta/metals#4699]
### Describe the bug

I am trying to rename the `smallest` to `biggest` in the `extractSmallest` def:

```scala
object Main extends App {

  def extractSmallest[T <% Ordered[T]](l: List[T]): (T, List[T]) = l match {
    case Nil         => (null.asInstanceOf[T], Nil)
    case head :: Nil => (head, Nil)
    case head :: tail => {
      val (smallest, remainder) = extractSmallest(tail)
      if (smallest < head) (smallest, head :: remainder)
      else (head, smallest :: remainder)
    }
  }

  def bubleSort[T <% Ordered[T]](l: List[T]): List[T] = l match {
    case Nil => Nil
    case _ => {
      val (smallest, remainder) = extractSmallest(l)
      smallest +: bubleSort(remainder)
    }
  }

  println(bubleSort(List(3, 5, 4, 1, 2)))
}

```

I'm getting:

```scala
object Main extends App {

  def extractSmallest[T <% Ordered[T]](l: List[T]): (T, List[T]) = l match {
    case Nil         => (null.asInstanceOf[T], Nil)
    case head :: Nil => (head, Nil)
    case head :: tail => {
      val (biggest, remainder) = extractSmallest(tail)
      if (biggest < head) (biggest, head :: remainder)
      else (head, smallest :: remainder)
    }
  }

  def bubleSort[T <% Ordered[T]](l: List[T]): List[T] = l match {
    case Nil => Nil
    case _ => {
      val (smallest, remainder) = extractSmallest(l)
      smallest +: bubleSort(remainder)
    }
  }

  println(bubleSort(List(3, 5, 4, 1, 2)))
}
```
One occurence of `smallest` is missing in the renamed

### Expected behavior

```scala
object Main extends App {

  def extractSmallest[T <% Ordered[T]](l: List[T]): (T, List[T]) = l match {
    case Nil         => (null.asInstanceOf[T], Nil)
    case head :: Nil => (head, Nil)
    case head :: tail => {
      val (biggest, remainder) = extractSmallest(tail)
      if (biggest < head) (biggest, head :: remainder)
      else (head, biggest :: remainder)
    }
  }

  def bubleSort[T <% Ordered[T]](l: List[T]): List[T] = l match {
    case Nil => Nil
    case _ => {
      val (smallest, remainder) = extractSmallest(l)
      smallest +: bubleSort(remainder)
    }
  }

  println(bubleSort(List(3, 5, 4, 1, 2)))
}
```

### Operating system

Linux

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

Latest Packer installed (0.11.9)

**Comment by jkciesluk** [comment]
Hi, thanks for reporting!
Which Scala version are you using?

I can't exactly reproduce this issue locally, but I've found a similar one:
```scala
def extractSmallest[T <% Ordered[T]](l: List[T]): (T, List[T]) = l match {
    case Nil         => (null.asInstanceOf[T], Nil)
    case head :: Nil => (head, Nil)
    case head :: tail => {
      val (biggest, remainder) = extractSmallest(tail)
      if (biggest < head) (biggest, head :: remainder)
      else (head, <<smallest>> :: remainder) // rename on this `smallest` has no effect
    }
  }
```
Although, this issue is fixed by https://github.com/scalameta/metals/pull/4694, so maybe yours will be too

**Comment by tgodzik** [comment]
I think the issue is with semanticdb, which isn't able to work properly with :: sometimes. This is the issue https://github.com/scalameta/scalameta/issues/2112

For local values, this should be fixed with PR @jkciesluk mentioned.

**Comment by kasiaMarek** [comment]
This rename is still broken. But now it simply fails to apply the rename, because of: https://github.com/scalameta/metals/issues/7086
