### ISSUE TITLE
Semantic highlighting uses weird styling for `end` def reference in a position where `end` marker is also acceptible

### ISSUE THREAD

**Issue by KacperFKorban** [scalameta/metals#5610]
### Describe the bug

1. Start with the following snippet

```scala
//> using scala 3.3.0

def end: Int =
  1

def notend: Int =
  1

class XD {
  def xd: Int =
    2
  end

  def xd2: Int =
    2
  notend
}
```

2. `scala-cli setup-ide filename.scala`
3. The `end` ident is bold, but `notend` is not.

### Expected behavior

The `end` def reference should have the same styling as any other def reference.

### Operating system

None

### Editor/Extension

VS Code

### Version of Metals

v1.0.1

### Extra context or search terms

semantic highlighting, scala 3

**Comment by kasiaMarek** [comment]
Thanks for the report. I followed your steps but `end` colouring seems to be as [expected](https://github.com/scalameta/metals/assets/26606662/e63e10bb-eb0b-4919-aae6-ae92c4ff046b) for me. 
Are you sure you have semantic highlighting properly enabled? It is now enabled by default in metals, but you still need to make sure it's also enabled in VSCode by setting `editor.semanticHighlighting.enabled` to `true`. More info can be found [here](https://scalameta.org/metals/blog/2023/03/02/aluminium/#introduce-support-for-semantic-tokens).

**Comment by kasiaMarek** [comment]
Both seem to have token type `method` with no additional modifiers resolved by metals. Maybe the boldness comes from some other scope and you have to override it. Maybe try running `Developer: Inspect Editor Tokens and Scopes` and inspecting them.

**Comment by KacperFKorban** [comment]
The semantic token type is `method`, but the textmate one is `keyword`. But looks like the `bold` style from the textmate grammar still gets applied.
![image](https://github.com/scalameta/metals/assets/39772805/b5abd396-8fd4-49e5-971a-bccd0538a51a)
Should the textmate styles be ignored when semantic highlighting is enabled?

**Comment by tgodzik** [comment]
> Should the textmate styles be ignored when semantic highlighting is enabled?

Looks like it is actually ignored but only partly, the color is override, but the fontStyle is not. Looks more like an issue with vs code itself or https://github.com/scala/vscode-scala-syntax <- a single end should not be a keyword.

Not much we can do in Metals itself.

**Comment by KacperFKorban** [comment]
Right, makes sense that the `vscode-scala-syntax` grammar should see the `end` as the same type of token.
Will close the issue here then, thanks for the answer.
