### ISSUE TITLE
Indexing runs forever in VSCode probably caused by an unexpected symbol

### ISSUE THREAD

**Issue by SidgranisSon** [scalameta/metals#6472]
### Describe the bug

We have an application based on these dependencies:
`libraryDependencies ++= Seq(
  "org.apache.kudu"  %% "kudu-spark3"               % "1.17.0",
  "org.apache.spark" %% "spark-sql"                 % "3.5.1" % "provided",
  "org.apache.spark"  % "spark-streaming_2.12"      % "3.5.1" % "provided",
  "org.apache.spark"  % "spark-sql-kafka-0-10_2.12" % "3.5.1" % "provided",
  "org.scalameta"    %% "munit"                     % "1.0.0" % Test
)`
When you open VSCode in a project with these dependencies, the VSCode extension builds the index forever. After a while I came across that within the projects .metals\.reports\metals-full\, there is a folder with some markdown files (attached) added which are all hinting in an indexing error caused by unexpected symbols.

```
error id: jar:file:///C:/Users/user/AppData/Local/Coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.4/hadoop-client-api-3.3.4-sources.jar!/org/apache/hadoop/tracing/TraceAdminPB.java
jar:file:///C:/Users/user/AppData/Local/Coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.4/hadoop-client-api-3.3.4-sources.jar!/org/apache/hadoop/tracing/TraceAdminPB.java

### java.lang.Exception: Unexpected symbol at word pos: '92'. Line: '      "mon.RemoveSpanReceiverResponseProtoB/\\n\031o" +'

Java indexer failed with and exception.
```

[2024-05-28.zip](https://github.com/user-attachments/files/15530611/2024-05-28.zip)

### Expected behavior

I expect that the index is built correctly.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v1.3.1

**Comment by tgodzik** [comment]
Thanks for repory, this should already be fixed in the latest snapshot. Could you try it out? I will most likely do a release next week or so since this seems a big issue for people

**Comment by SidgranisSon** [comment]
Thanks for the quick response, I activated the pre release version of the plugin (Last updated: 2024-06-03, 13:29:02), but I still get the same error markdown files and the index runs already more then 5 minutes.

**Comment by kasiaMarek** [comment]
Oh, that won't be enough in this case. You need to manually set `Metals: Server Version` to the current snapshot in settings. Here you can find the current snapshot: https://scalameta.org/metals/docs/.

**Comment by shrukul** [comment]
I was facing the same issue - Indexing taking forever, and never completing in my case. Switching to pre-release and manually updating the `Metals: Server Version` fixed it. Thanks!

**Comment by SidgranisSon** [comment]
> Oh, that won't be enough in this case. You need to manually set `Metals: Server Version` to the current snapshot in settings. Here you can find the current snapshot: https://scalameta.org/metals/docs/.

Thanks for this update! I managed to install the latest snapshot version and I can verify that the index doesn't run infinite anymore. But I recognized, that the error markdown files are still generated, did you fix the parsing or did you improve the error handling?

Cheers :)

**Comment by kasiaMarek** [comment]
> But I recognized, that the error markdown files are still generated, did you fix the parsing or did you improve the error handling?

There is an error in the library sources in this case (those are generated). You can see it in the PR in comment here: https://github.com/scalameta/metals/pull/6321. So we just improved error handling.

Closing this as completed.

**Comment by SidgranisSon** [comment]
Perfect, thanks for your quick reply and for fixing the problem that quickly!

**Comment by felipepessoto** [comment]
Any ETA to release a non-snapshot version with the fix?

Thanks

**Comment by tgodzik** [comment]
We plan to do a release next week.
