### ISSUE TITLE
Zombie metals

### ISSUE THREAD

**Issue by eed3si9n** [scalameta/metals#869]
Ref https://github.com/scalameta/metals/issues/723#issuecomment-497947731

**Describe the bug**
There are multiple zombie JVM process that accumulate over time even if I close VS Code.
The oldest was almost a month old.

**To Reproduce**
1. I am not sure, but if you keep using metals for a while.
2. Quit VS Code.
3. `jps -l | grep scala.meta.metals.Main`

**Expected behavior**
No zombie processes.

**JStack**

<details>

```
2019-08-23 01:15:04
Full thread dump OpenJDK 64-Bit Server VM (25.212-b03 mixed mode):

"Attach Listener" #1581 daemon prio=9 os_prio=31 tid=0x00007ff12df9d800 nid=0x766b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"DestroyJavaVM" #1578 prio=5 os_prio=31 tid=0x00007ff12c80b800 nid=0x1903 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"AsyncReporter{URLConnectionSender{http://127.0.0.1:9411/api/v2/spans}}" #333 daemon prio=5 os_prio=31 tid=0x00007ff12d840800 nid=0xad07 waiting on condition [0x000070000effa000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c5a7fc68> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at zipkin2.reporter.ByteBoundedQueue.drainTo(ByteBoundedQueue.java:81)
	at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:257)
	at zipkin2.reporter.AsyncReporter$Builder$1.run(AsyncReporter.java:190)

"monix-scheduler-99" #99 daemon prio=5 os_prio=31 tid=0x00007ff1278cc000 nid=0x13403 waiting on condition [0x0000700018c6f000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c1c0c310> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Scala Presentation Compiler [Metals]" #97 daemon prio=5 os_prio=31 tid=0x00007ff125da8000 nid=0xbc03 in Object.wait() [0x000070001886c000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c16a9118> (a scala.tools.nsc.util.WorkScheduler)
	at java.lang.Object.wait(Object.java:502)
	at scala.tools.nsc.util.WorkScheduler.waitForMoreWork(WorkScheduler.scala:28)
	- locked <0x00000006c16a9118> (a scala.tools.nsc.util.WorkScheduler)
	at scala.tools.nsc.interactive.MetalsGlobalThread.$anonfun$run$2(MetalsGlobalThread.scala:22)
	at scala.tools.nsc.interactive.MetalsGlobalThread$$Lambda$2910/352755478.apply$mcZ$sp(Unknown Source)
	at scala.tools.nsc.interactive.NullLogger$.logreplay(Replayer.scala:50)
	at scala.tools.nsc.interactive.MetalsGlobalThread.run(MetalsGlobalThread.scala:21)

"Scala Presentation Compiler []" #96 daemon prio=5 os_prio=31 tid=0x00007ff12759a800 nid=0x13703 in Object.wait() [0x0000700018469000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000006c16a9118> (a scala.tools.nsc.util.WorkScheduler)
	at java.lang.Object.wait(Object.java:502)
	at scala.tools.nsc.util.WorkScheduler.waitForMoreWork(WorkScheduler.scala:28)
	- locked <0x00000006c16a9118> (a scala.tools.nsc.util.WorkScheduler)
	at scala.tools.nsc.interactive.PresentationCompilerThread.$anonfun$run$2(PresentationCompilerThread.scala:28)
	at scala.tools.nsc.interactive.PresentationCompilerThread$$Lambda$2894/865618773.apply$mcZ$sp(Unknown Source)
	at scala.tools.nsc.interactive.NullLogger$.logreplay(Replayer.scala:50)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:28)

"pool-12-thread-1" #55 prio=5 os_prio=31 tid=0x00007ff121d1f000 nid=0x6603 waiting on condition [0x000070000e7f4000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0ab2720> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:550)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-5-thread-6" #45 daemon prio=5 os_prio=31 tid=0x00007ff122909800 nid=0x8d03 waiting on condition [0x000070000cfe2000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0389f48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-5-thread-5" #44 daemon prio=5 os_prio=31 tid=0x00007ff124c3f800 nid=0x6203 waiting on condition [0x000070000cbdf000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0389f48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-5-thread-4" #43 daemon prio=5 os_prio=31 tid=0x00007ff1268a4800 nid=0x9003 waiting on condition [0x000070000c7dc000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0389f48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-5-thread-3" #42 daemon prio=5 os_prio=31 tid=0x00007ff124c3f000 nid=0x6103 waiting on condition [0x000070000c3d9000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0389f48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-5-thread-2" #37 daemon prio=5 os_prio=31 tid=0x00007ff123079000 nid=0x5e03 waiting on condition [0x000070000afca000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0389f48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"pool-5-thread-1" #36 daemon prio=5 os_prio=31 tid=0x00007ff123078000 nid=0x9a03 waiting on condition [0x000070000abc7000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0389f48> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Service Thread" #9 daemon prio=9 os_prio=31 tid=0x00007ff121807800 nid=0x4103 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #8 daemon prio=9 os_prio=31 tid=0x00007ff123803800 nid=0x3f03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #7 daemon prio=9 os_prio=31 tid=0x00007ff123803000 nid=0x4603 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007ff123802000 nid=0x3d03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=31 tid=0x00007ff123800800 nid=0x3b03 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 tid=0x00007ff123005000 nid=0x4703 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=31 tid=0x00007ff12181c800 nid=0x4f03 in Object.wait() [0x0000700006e8e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x00000006c01daac8> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=31 tid=0x00007ff125006000 nid=0x3603 in Object.wait() [0x0000700006a8b000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000006c01dab08> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"VM Thread" os_prio=31 tid=0x00007ff12482c000 nid=0x3403 runnable 

"GC task thread#0 (ParallelGC)" os_prio=31 tid=0x00007ff121817800 nid=0x2007 runnable 

"GC task thread#1 (ParallelGC)" os_prio=31 tid=0x00007ff121818000 nid=0x2a03 runnable 

"GC task thread#2 (ParallelGC)" os_prio=31 tid=0x00007ff121818800 nid=0x2c03 runnable 

"GC task thread#3 (ParallelGC)" os_prio=31 tid=0x00007ff121819800 nid=0x2d03 runnable 

"GC task thread#4 (ParallelGC)" os_prio=31 tid=0x00007ff12181a000 nid=0x2f03 runnable 

"GC task thread#5 (ParallelGC)" os_prio=31 tid=0x00007ff12181a800 nid=0x5303 runnable 

"GC task thread#6 (ParallelGC)" os_prio=31 tid=0x00007ff12181b000 nid=0x3103 runnable 

"GC task thread#7 (ParallelGC)" os_prio=31 tid=0x00007ff12181c000 nid=0x3303 runnable 

"VM Periodic Task Thread" os_prio=31 tid=0x00007ff121829800 nid=0x4303 waiting on condition 

JNI global references: 12041

```
</details>

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.7.0

**Additional context**

**Search terms**

**Comment by marek1840** [comment]
Do you have more zombies when terminating vscode than there were before launching it?
Can you provide the number of zombies before and after hibernating your machine?

**Comment by olafurpg** [comment]
Thank you for reporting! In your tweet you mentioned some processes were older than a few months. Do you know what version of Metals the most recent process was from? In 0.7 we fixed several issues related to killing the presentation compiler thread.

**Comment by eed3si9n** [comment]
> Do you have more zombies when terminating vscode than there were before launching it?

If I just open VS Code with a Scala project, trigger code completion, and quit VS Code, there are no zombies; so it doesn't always happen. (iow, Presentation Compiler thread or whatever that gets stuck, doesn't always gets stuck). Hibernating doesn't seem to cause issues either.

> Do you know what version of Metals the most recent process was from?

One of them said "Sat12PM", so I am guessing that's last Saturday, and that should be a fairly recent version of Metals. It's currently 1.5.2.

**Comment by tgodzik** [comment]
We still didn't fix the issue in tests:
```
INFO  tests.TestingServer#didOpen
Exception in thread "pool-47-thread-1" java.lang.Error: scala.tools.nsc.interactive.ShutdownReq$
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: scala.tools.nsc.interactive.ShutdownReq$
X tests.DefinitionSlowSuite.annotations 20689ms 
  java.util.concurrent.CancellationException
  java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2263)
  scala.meta.internal.pc.CompilerAccess.$anonfun$onCompilerJobQueue$4(CompilerAccess.scala:208)
  scala.meta.internal.pc.CompilerAccess.$anonfun$onCompilerJobQueue$4$adapted(CompilerAccess.scala:205)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)

```

I think that might be connected - Metals themselves do not have a timeout so it will get stuck in a situation like this.

**Comment by bobrowadam** [comment]
@eed3si9n I also get this issue using emacs with metals. Were you able to kill those processes? When I try to kill them I get "Operation not permitted".

**Comment by eed3si9n** [comment]
I have not come across zombie metals that I couldn't kill. I normally use macOS.

**Comment by tgodzik** [comment]
@bobrowadam it shouldn't be an issue - we can't start processes that you are not able to kill I think :thinking:

**Comment by jvican** [comment]
[Here](https://gist.github.com/jvican/a4a081718ac330de3aa734fdfd665085) is a Gist with three jstack traces of Metals processes, out of which two traces come from zombie processes and one comes from a healthy server (I haven't identified which one is what, I only know there should only be one Metals server running). I remember I've done several `Reload window` and `Import Build` during the last hours.

**Comment by eed3si9n** [comment]
If VS Code extension is supposed to clean up the Java process, I wonder if we should look into scalameta/metals-vscode more closely rather than the server code itself.

For example, for vscode-sbt-scala I registered `deactivate()` method in `extension.ts` that does the cleanup. https://github.com/sbt/sbt/blob/2f31849c64957592d992a55c71b0bfe393166681/vscode-sbt-scala/client/src/extension.ts#L24-L30

**Comment by tgodzik** [comment]
Awesome! Thanks @jvican!

**Comment by tgodzik** [comment]
1 and 3 seem to have a process called DestroyJavaVm, so I guess they are being shutdown albeit not successfully 🤔

**Comment by tgodzik** [comment]
@jvican the only running threads seem to be the ones from Bloop Gun, could they be holding up the JVM?

**Comment by jvican** [comment]
@tgodzik Are we sure that these threads hold up the JVM? This issue was created a long time ago so I'm not sure the bloopgun threads are to blame. I'm open to giving that a try, I'll be reviewing your PR shortly.

**Comment by tgodzik** [comment]
> @tgodzik Are we sure that these threads hold up the JVM? This issue was created a long time ago so I'm not sure the bloopgun threads are to blame. I'm open to giving that a try, I'll be reviewing your PR shortly.

Not 100% sure, but those are the only Runnable ones and from what I read DestroyJavaVm will wait for those. And would make sense to make those deamon threads.

**Comment by jvican** [comment]
Agreed, I don't remember why they're not daemon, need to look into that when I review.

**Comment by pjhenning** [comment]
Hello, I've been encountering this lately, perhaps the issue should be re-opened?

**Comment by tgodzik** [comment]
Sure, but would you be able to provide some stack traces or any more information? Otherwise, I haven't seen this happen again, so this would be not possible for us to fix.
